#!/bin/bash
if [ -d /home/6mASCOPE/SLpackage ];then
echo "Remove old SMRTLink package ..."
rm -rf /home/6mASCOPE/SLpackage
echo "Download new SMRTLink package ..."
#git clone https://github.com/yimengkong/SLpackage.git /home/6mASCOPE/SLpackage
git init
git remote add -f origin https://github.com/yimengkong/6mASCOPE.git
git config core.sparseCheckout true
echo "SLpackage" >> .git/info/sparse-checkout
git pull origin master
rm -rf .git
else
echo "Download SMRTLink package from github..."
#git clone https://github.com/yimengkong/SLpackage.git /home/6mASCOPE/SLpackage
git init
git remote add -f origin https://github.com/yimengkong/6mASCOPE.git
git config core.sparseCheckout true
echo "SLpackage" >> .git/info/sparse-checkout
git pull origin master
rm -rf .git
ln -s /home/6mASCOPE/SLpackage/private/pacbio/pythonpkgs/kineticstools/binwrap/ipdSummary /usr/local/bin/
ln -s /home/6mASCOPE/SLpackage/private/pacbio/pythonpkgs/pbalign/binwrap/pbalign /usr/local/bin/
fi
#parallel --citation 1>/dev/null 2>/dev/null

if [ -d /home/6mASCOPE/database/nt-pre-build ];then
echo "Remove old pre-build nt database ..."
rm -rf /home/6mASCOPE/database/nt-pre-build
echo "Download new pre-build nt database ..."
else
echo "Download pre-build nt database..."
fi
mkdir /home/6mASCOPE/database/nt-pre-build
cd /home/6mASCOPE/database/nt-pre-build
for x in 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60;do for y in nhd nhi nhr nin nnd nni nog nsd nsi nsq;do wget https://nt-pre-build.s3.us-east-2.amazonaws.com/nt-pre-build-tar/nt."$x"."$y".tar.gz;done ;done
wget "https://nt-pre-build.s3.us-east-2.amazonaws.com/nt-pre-build-tar/nt.nal.tar.gz"
wget "https://nt-pre-build.s3.us-east-2.amazonaws.com/nt-pre-build-tar/taxdb.btd.tar.gz"
wget "https://nt-pre-build.s3.us-east-2.amazonaws.com/nt-pre-build-tar/taxdb.bti.tar.gz"
find . -name "*.tar.gz" -type f -exec tar -zxvf {}  \; -exec  rm -rf {}  \; > /dev/null

cd /home/6mASCOPE
source /home/6mASCOPE/.bashrc
#eval "$(conda shell.bash hook)"
#conda activate 6mASCOPE
#6mASCOPE $@
