#!/bin/bash

# ---- error handling
set -o errexit;
set -o posix;
set -o pipefail;
set -o errtrace;
unexpected_error() {
    local errstat=$?
    echo "${g_prog:-$(basename "$0")}: Error! Encountered unexpected error at 'line $(caller)', bailing out..." 1>&2
    exit $errstat;
}
trap unexpected_error ERR;

# Force the path to only what we need, saving off the original path
PATH_ORIG=$PATH;
PATH=/usr/bin:/bin
g_prog=$(basename "$0");
g_progdir=$(dirname "$0");
g_progdir_abs=$(dirname "$(readlink -f "$0")");

# ---- globals

g_exe="${g_progdir_abs}/../../../../../private/pacbio/pythonpkgs/pbalign/bin/pbalign";

g_executor_exe="${g_progdir_abs}/../../../../../private/thirdparty/python/python_2.7.16/binwrap/python";

g_path=""
g_path="$g_path:${g_progdir_abs}/../../../../../private/thirdparty/samtools/samtools_1.9/binwrap";
g_path="$g_path:${g_progdir_abs}/../../../../../private/pacbio/blasr/binwrap";
g_path=${g_path#:}

# --- global env
. "${g_progdir_abs}/../../../../../private/runtime-common/lib/globalenv.ish"

# ---- main

__SMRTPRIVATE_EXEPATH__samtools="${g_progdir_abs}/../../../../../private/thirdparty/samtools/samtools_1.9/binwrap/samtools" \
__SMRTPRIVATE_EXEPATH__blasr="${g_progdir_abs}/../../../../../private/pacbio/blasr/binwrap/blasr" \
PATH="$g_path:${PATH_ORIG}" \
    exec "$g_executor_exe" "$g_exe"  ${1+"$@"}
