#!/bin/bash

# ---- error handling
set -o errexit;
set -o posix;
set -o pipefail;
set -o errtrace;
unexpected_error() {
    local errstat=$?
    echo "${g_prog:-$(basename "$0")}: Error! Encountered unexpected error at 'line $(caller)', bailing out..." 1>&2
    exit $errstat;
}
trap unexpected_error ERR;

function bn() { local name="${1##*/}"; echo "${name%$2}"; }
function dn(){ local d="${1%${1##*/}}"; [[ x"${d:=./}" != x"/" ]] && d=${d%?};echo "$d";}

g_prog=$(bn "$0");
g_progdir=$(dn "$0");
#g_progdir_abs=$(cd "$g_progdir" && pwd -P)
g_progdir_abs=$(cd "$(dn "$(readlink -f "$0")")" && pwd -P)

# ---- global env

. "${g_progdir_abs}/../../../../private/runtime-common/lib/globalenv.ish";

# ----- main

# Call java with the one-jar file directly
exec "$g_progdir_abs/../../../thirdparty/jre/jre_8u192b12-hotspot/bin/java" -Xmx3300m -Xms256m -jar $g_progdir_abs/../lib/MotifMaker-assembly-0.3.3.jar ${1+"$@"}
